config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'  
   
  end

  resources :categories do
    resources :tasks do
    end
  end



  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root 'dashboard#index'
  get 'dashboard/index'


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :tasks, dependent: :destroy
    validates :title, presence: true
    validates :description, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  validates :title, presence: true
  validates :description, presence: true
  validates :due_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_category, only: [:show, :edit, :update, :destroy]
      
    def index
      @categories = current_user.categories
    end
  
    def show
    end
  
    def new
      @category = current_user.categories.build
    end
  
    def create
      @category = current_user.categories.build(category_params)
  
      if @category.save
        redirect_to category_path(@category), notice: 'Successfully created new category'
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def edit
    end
  
    def update
      if @category.update(category_params)
        redirect_to category_path(@category), notice: 'Successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      @category.destroy
      redirect_to dashboard_index_path, notice: 'Successfully deleted the category.'
    end
  
    private
  
    def set_category
      @category = current_user.categories.find(params[:id])
    end
  
    def category_params
      params.require(:category).permit(:title, :description)
    end
  end
  

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @date_today = Date.today
        @categories = current_user.categories.includes(:tasks)
        @tasks_due = @categories.flat_map { |category| category.tasks.where(due_date: @date_today.all_day) }
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!
    before_action :set_category
    before_action :set_task, only: [:show, :edit, :update, :destroy]
  
    def index
      @tasks = @category.tasks
    end
  
    def show
  
    end
  
    def new
      @task = @category.tasks.build
    end
  
    def create
      @task = @category.tasks.build(task_params)
  
      if @task.save
        redirect_to category_task_path(@category, @task), notice: 'Successfully created new task.'
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def edit
      
    end
  
    def update
      if @task.update(task_params)
        redirect_to category_task_path(@category, @task), notice: 'Successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      @task.destroy
      redirect_to category_path(@category), notice: 'Successfully deleted the task.'
    end

    private
    
    def set_category
      @category = current_user.categories.find(params[:category_id])
    end
  
    def set_task
      @task = @category.tasks.find(params[:id])
    end
  
    def task_params
      params.require(:task).permit(:title, :description, :due_date, :done)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, url: category.persisted? ? category_path(category) : categories_path, local: true) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-wrapper'>
    <div class='form-body'>
      <div class='form-input'>
        <%= form.label :title, class: 'form-label' %><br>
        <%= form.text_field :title, class: 'form-field' %>
      </div>

      <div class='form-input'>
        <%= form.label :description, class: 'form-label' %><br>
        <%= form.text_area :description, class: 'form-field text-area' %>
      </div>

      <div class='form-input'>
        <%= form.submit class: 'button' %>
      </div>
    </div>

  </div>
<% end %>

app/views/categories/edit.html.erb
<div class='form-pages'>
  <div class='form-top'>
    <h1 class='page-title form-header'>EDIT CATEGORY</h1>
    <div>
      <%= link_to "BACK TO #{@category.title}", category_path(@category) %>
    </div>
  </div>


  <div class='form-proper'>
    <%= render "form", category: @category %>
  </div>

</div>

app/views/categories/index.html.erb
<% if user_signed_in? %>
<p class='notice-container'><%= notice %></p>
<div class='wrapper'>
  <div class='page-top'>
    <h1 class='page-title'>Categories</h1>
    <span class='add-btn'><%= link_to "+", new_category_path %></span>
  </div>
  

  <div class='page-body'>
    <% current_user.categories.each do |category| %>
      <%= render category %>
      <div class='indiv-categ'>
        <h2 class='categ-title'><%= link_to(category.title, category_path(category)) %></h2>
        <p class='categ-description'><%= truncate(category.description, length: 100) %></p>
        
      </div>
    <% end %>
  </div>
  
</div>

<% else %>
  <%= link_to 'Sign in', new_user_session_path %> |
  <%= link_to 'Sign up', new_user_registration_path %>
<% end %>

app/views/categories/new.html.erb
<div class='form-pages'>
  <div class='form-top'>
    <h1 class='page-title form-header'>NEW CATEGORY</h1>
  </div>

  <div class='form-proper'>
  <%= render "form", category: @category %>
  </div>
  
</div>

app/views/categories/show.html.erb
<div class = 'category-wrapper'>
  <p style="color: green"><%= notice %></p>

  <div class='categ-card'>
    <div class = 'categ-card-top'>
      <h1 class='categ-page-title'><%= @category.title %></h1>
    </div>

    <div class='categ-card-body'>
      <div class='categ-desc-container'>
        <p class ='categ-page-desc'><%= @category.description %></p>
      </div>
      <div class = 'button-panel'>
        <%= link_to "EDIT", edit_category_path(@category) %> |
        <%= button_to "DELETE", @category, method: :delete, class:'dlt-button' %>
      </div>
    </div>
  </div>

  <div class='wrapper'>
    <div class='page-top'>
      <h1 class='page-title-task'>Tasks</h1>
      <span class='add-btn'><%= link_to "+", new_category_task_path(@category) %></span>
    </div>

    <div class='page-body'>
    <% @category.tasks.each do |task| %>
       <%= render task %>
        <div class='indiv-task'>
          <div class='categ-task-top'>
            <h2 class='categ-title'><%= link_to task.title, category_task_path(@category, task)%></h2>
            <p <%= task.done ? "class= done-task" :  "class= undone-task" %>>
              <%= task.done ? 'Done' : 'Undone' %>
            </p>
          </div>
          <p class='task-due'>Due Date: <%= task.due_date.strftime("%B %e, %Y") %></p>
          <p class='categ-description'><%= truncate(task.description, length: 90) %></p>
        
      
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<% if user_signed_in? %>
  <p class='notice-container'><%= notice %></p>
  
  <div class='wrapper'>
    <div class='date-time-container'>
      <%= Time.now.strftime('%d %b %Y %H:%M:%S') %>
    </div>

    <div class='container'>  
     
      <div class='page-top'>
        <h1 class='page-title'>Tasks Due Today</h1>
      </div>
    
      <div class='page-body'>
        <% @tasks_due.each do |task| %>
          <%= render task %>
          <div class='indiv-task'>
            <div class='categ-task-top'>
              <h2 class='categ-title'><%= link_to task.title, category_task_path(task.category, task)%></h2>
              <p <%= task.done ? "class= done-task" : "class= undone-task" %>>
                <%= task.done ? 'Done' : 'Undone' %>
              </p>
            </div>
            <div class='body-task-card'>
              <p class='task-due'>Due Date: <%= task.due_date.strftime("%d %b %Y") %></p>
              <p class='body-task-rows'>Category: <%= link_to task.category.title, category_path(task.category) %></p>
              <p class='body-task-rows'><%= truncate(task.description, length: 90) %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class='container'>
      
      <div class='page-top'>
        <h1 class='page-title'>Overdue Tasks</h1>
      </div>

      <div class='page-body'>
        <% current_user.categories.each do |category| %>
          <% category.tasks.select { |task| !task.done && task.due_date < Date.today }.each do |task| %>
            <div class='indiv-task'>
              <div class='categ-task-top'>
                <h2 class='categ-title'><%= link_to task.title, category_task_path(task.category, task) %></h2>
                <p class='undone-task'>Undone</p>
              </div>
              <div class='body-task-card'>
                <p class='task-due'>Due Date: <%= task.due_date.strftime("%d %b %Y") %></p>
                <p class='body-task-rows'>Category: <%= link_to task.category.title, category_path(task.category) %></p>
                <p class='body-task-rows'><%= truncate(task.description, length: 90) %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class='container'>
      
      <div class='page-top'>
        <h1 class='page-title'>Categories</h1>
        <span class='add-btn'><%= link_to "+", new_category_path %></span>
      </div>
     
      <div class='page-body'>
        <% current_user.categories.each do |category| %>
          <%= render category %>
          <div class='indiv-categ'>
            <h2 class='categ-title'><%= link_to(category.title + " (#{category.tasks.count})", category_path(category)) %></h2>
            <p class='categ-description'><%= truncate(category.description, length: 100) %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>

<% else %>
  <%= link_to 'Sign in', new_user_session_path %> |
  <%= link_to 'Sign up', new_user_registration_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Journal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class='nav-bar'>
    <div class='app-title'>
        <% if user_signed_in? %>
        <div class='user-info'>
            <p class='logged-user'><%= current_user.email %></p>
            <p class='member-since'>Member since: <span class='member-date'><%= current_user.created_at.strftime("%d %b %Y") %></span></p>
        </div>
        <% else %>
        <h1 class='app-name'>Rails<span class='journal-text'>Journal</span></h1>
        <% end %>
    </div>

    <div class='nav-button'>
        <ul class='nav-ul'>
        <% if user_signed_in? %>
            <li class='nav-li'><%= link_to 'Home', dashboard_index_path %></li>
            <li class='nav-li'><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li class='nav-li'><%= link_to 'Log in', new_user_session_path %></li>
            <li class='nav-li'><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
        </ul>
    </div>
</nav>

app/views/tasks/_form.html.erb
<%= form_with(model: [@category, @task]) do |form| %>
  <% if @task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% @task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class='form-wrapper'>
    <div class='form-body'>
      <div class='form-input'>
        <%= form.label :title, class: 'form-label' %><br>
        <%= form.text_field :title, class: 'form-field' %>
      </div>

      <div class='form-input'>
        <%= form.label :description, class: 'form-label' %><br>
        <%= form.text_area :description, class: 'form-field text-area' %>
      </div>

      <div class='form-input'>
        <%= form.label :due_date, class: 'form-label' %><br>
        <%= form.date_field :due_date, class: 'form-field' %>
      </div>

      <div class='form-input'>
        <%= form.label :status, class: 'form-label' %><br>
        <div class='radio-options'>
        <%= form.radio_button :done, false, class: 'form-field-radio', checked: !@task.done %> Undone
        <%= form.radio_button :done, true, class: 'form-field-radio', checked: @task.done %> Done
        </div>
      </div>

      <div class='form-input'>
        <%= form.submit class: 'button' %>
      </div>
    </div>

  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
</div>

app/views/tasks/edit.html.erb
<div class='form-pages'>
  <div class='form-top'>
    <h1 class='page-title form-header'>EDIT TASK</h1>
    <div>
      <%= link_to "BACK TO #{@task.title}", category_task_path(@category, @task) %>
    </div>
  </div>


  <div class='form-proper'>
    <%= render "form", task: @task %>
  </div>

</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks under <%= @category.title %></h1>

<div id="tasks">
  <% if @tasks.any? %>
    <% @tasks.each do |task| %>
      <h2><%= task.title %></h2>
      <p><%= task.description %></p>
      <p>
        <%= link_to 'Show', category_task_path(@category, task) %>
      </p>
    <% end %>
  <% else %>
    <p>No tasks found.</p>
  <% end %>
</div>

<div>
  <%= link_to "Back to #{@category.title}", category_path(@category) %> |
  <%= link_to 'New task', new_category_task_path(@category) %>
</div>

app/views/tasks/new.html.erb
<div class='form-pages'>
  <div class='form-top'>
    <h1 class='page-title form-header'>NEW TASK</h1>
    <%= link_to "BACK TO #{@category.title}", category_path(@category) %>
  </div>

  <div class='form-proper'>
    <%= render "form", task: @task %>
  </div>
  
</div>

app/views/tasks/show.html.erb
<p style="color: green; display: flex; justify-content: center;"><%= notice %></p>

<div class='task-card'>
    <div class= 'task-card-top'>
      <h1 class='task-title'><%= @task.title %></h1>
    </div>

    <div class='task-card-body'>
      <p class='task-label'>DUE DATE: <span class='due-date'><%= @task.due_date.strftime("%B %e, %Y") %></span></p>
      <p class='task-label'>STATUS:<span class='status'>
        <% if @task.done %>
          Done
        <% else %>
          Undone
        <% end %>
      </span></p>
      <p class='task-label'>DETAILS: <span class='task-description'><%= @task.description %></span></p>
  
      <div class = 'button-panel task-buttons'>
        <%= link_to 'Edit', edit_category_task_path(@category, @task) %> |
        <%= link_to "#{@category.title}", category_path(@category) %> |
        <%= button_to 'Delete', category_task_path(@category, @task), method: :delete, class:'dlt-button' %>
      </div>
    </div>
</div>